version: "3.7"

networks:
  rabbitmq_network:
    name: ${NETWORK_NAME}

services:
  rabbitmq:
    image: "rabbitmq:${RABBITMQ_IMAGE_VERSION}"
    ports:
      - "${RABBITMQ_PORT}:15672"
    volumes:
      - "./config/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    networks:
      - rabbitmq_network

